### ISSUE TITLE
Slider issues. 

### ISSUE THREAD

**Issue by xiUnknown1** [Sk1erLLC/Vigilance#31]
As seen here, some sliders sometimes open/closes on you when trying to change the value of a setting + IMO its too sensitive, moving your mouse slightly upwards would cause it to close too.

https://user-images.githubusercontent.com/84973878/136683923-5c8d60b3-e83f-482e-a049-86a0ccfce48a.mp4

Also here, hovering on the top of some sliders would cause it to shake more than my sleeping cat.

https://user-images.githubusercontent.com/84973878/136684024-353e1879-6e33-4e55-802f-28d836b4611b.mp4

**Comment by asbyth** [comment]
I believe we planned on making the slider expand once the entire option was hovered over, not just the slider itself. Not sure what happened to that, though

**Comment by LlamaLad7** [comment]
Nope, turns out they disabled it deliberately. No idea why.
