### ISSUE TITLE
Stupid question, what is the current build number

### ISSUE THREAD

**Issue by xXBannedXx** [Sk1erLLC/Vigilance#32]
192 as suggested in the readme is not working

**Comment by Sychic** [comment]
Current builds are 189 for all versions.

**Comment by xXBannedXx** [comment]
Am I doing something wrong? I have the sk1er repo added and `implementation "gg.essential:vigilance-1.8.9-forge:189+mc-1.18"` but gradle is unable to find it.

**Comment by Sychic** [comment]
what you want is `implementation "gg.essential:vigilance-1.8.9-forge:189"`

**Comment by xXBannedXx** [comment]
that's what I tried first, it didn't work either, is the repo down?

**Comment by Sychic** [comment]
No, can you send your build.gradle in the elementa and vigilance channel in our discord? https://discord.gg/sk1er

**Comment by xXBannedXx** [comment]
I am using [https://github.com/asbyth/ForgeTemplate](https://github.com/asbyth/ForgeTemplate) and added the repo to settings.gradle and added dependencies in build.gradle

**Comment by Sychic** [comment]
You may have added the repo incorrectly, please head on over to our discord for help.

**Comment by Sychic** [comment]
Cheat thread
