### ISSUE TITLE
How can I change the width and height of config components?

### ISSUE THREAD

**Issue by CommandCracker8** [Sk1erLLC/Vigilance#39]
Hiya

When I use .setHeiight or .setWidth it doesn't work properly, what should I do?

**Comment by CommandCracker8** [comment]
Ah okay. I was only using it for an Elementa GUI so I can copy the code and just change it myself :) Assuming your license allows that?

**Comment by Sychic** [comment]
Wait are you talking about within vigilance's gui or your own gui? If it's your own gui you should be able to constrain it (depending on which one it is)

**Comment by CommandCracker8** [comment]
Okay 👍
