### ISSUE TITLE
Slider value positioning

### ISSUE THREAD

**Issue by asbyth** [Sk1erLLC/Vigilance#4]
Having a max value too high will set the x position of the max value way too far to the right, and the current value isn't aligned with the slider knob
![image](https://user-images.githubusercontent.com/36578995/77784366-c8555c80-7030-11ea-9fcf-02f59e8463be.png)

**Comment by FalseHonesty** [comment]
Fixed in 4ad5b0c3ba9037200fab663e1904a22be3627556 and 46259763a6e577bce8ef1e656d639dd3ec5a8815.

**Comment by asbyth** [comment]
poggers

**Comment by asbyth** [comment]
![image](https://user-images.githubusercontent.com/36578995/79024116-f6b65a00-7b4f-11ea-9130-f10541407217.png)
Now it's the other way around

**Comment by FalseHonesty** [comment]
:(
