### ISSUE TITLE
Arrow keys allow for slider number to go past min/max

### ISSUE THREAD

**Issue by asbyth** [Sk1erLLC/Vigilance#5]
Using the arrow keys, you can go past the min/max value
![image](https://user-images.githubusercontent.com/36578995/79021030-7dffcf80-7b48-11ea-930b-f1dcd4ccc7ea.png)

**Comment by FalseHonesty** [comment]
Fixed in 67c61934b77a4a297c3d85b341ac4832f1359a2b.
